name: Android CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 1. تنصيب أداة الجرافيكس من نظام لينكس مباشرة
      - name: Install glslangValidator
        run: |
          sudo apt-get update
          sudo apt-get install -y glslang-tools

      # 2. بناء التطبيق وتجاوز فحص النسخ
      - name: Build APK
        run: |
          # البحث عن ملف التشغيل
          GRADLEW_PATH=$(find . -name gradlew | head -n 1)
          chmod +x $GRADLEW_PATH
          cd $(dirname $GRADLEW_PATH)
          
          # إجبار النظام على استخدام الأداة التي نصبناها في الخطوة 1
          ./gradlew assembleMainlineDebug \
            -Pandroid.externalNativeBuild.cmake.arguments="-DGLSLANG_VALIDATOR=/usr/bin/glslangValidator" \
            -Pandroid.plugin.v3.check=false

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Eden-Huawei-Maleoon-Edition
          path: |
            **/build/outputs/apk/mainline/debug/*.apk