name: Android CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Install Graphics Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y glslang-tools ninja-build
          # التحقق من وجود الأداة للتأكد فقط
          glslangValidator --version

      - name: Build APK
        run: |
          GRADLEW_PATH=$(find . -name gradlew | head -n 1)
          chmod +x $GRADLEW_PATH
          cd $(dirname $GRADLEW_PATH)
          
          # البناء النهائي مع تمرير مسار الأداة المؤكد
          ./gradlew assembleMainlineDebug \
            -Dorg.gradle.daemon=false \
            -Pandroid.plugin.v3.check=false \
            -Pandroid.externalNativeBuild.cmake.arguments="-DGLSLANG_VALIDATOR=/usr/bin/glslangValidator"

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Eden-Huawei-Maleoon-Edition
          path: |
            **/build/outputs/apk/mainline/debug/*.apk